"use client";

import React, { useState } from "react";
import Link from "next/link";
import { ChevronDown, Sparkles, AlertCircle } from "lucide-react";

const FAQS_LIST = [
  { q: "How does the ₹5,000 online exclusive discount work?", a: "When you book your vehicle through our self-serve website by making your refundable booking deposit, a ₹5,000 flat discount is automatically locked to your profile. This amount is subtracted directly from the final ex-showroom invoice at the dealership." },
  { q: "Is my booking deposit fully refundable?", a: "Yes. Laxmi Toyota offers a 100% refund policy. If you choose to cancel your booking for any reason prior to vehicle invoicing and registration, we will return the entire deposit to your original payment method within 5-7 working days." },
  { q: "What documents are required to complete the registration?", a: "You will need a valid Aadhaar Card, PAN Card, address proof, and passport-size photographs. For corporate and government employee benefits, you will also be required to provide a company ID card or official pay slip." },
  { q: "How can I check the waiting period for my vehicle?", a: "Each model detail card displays its live stock allocation status. In-stock models are available for immediate delivery within 7 days, whereas waitlisted models range from 4 to 12 weeks depending on factory production timelines." },
  { q: "Can I change my vehicle color or variant after booking?", a: "Yes. You can update your variant specifications or exterior color preferences anytime before the official dealer invoice is generated by getting in touch with your assigned Sales Advisor." }
];

export default function FaqsPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 py-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto space-y-12">
        
        {/* Header */}
        <div className="space-y-4 text-center">
          <span className="text-[10px] font-bold tracking-widest uppercase text-[#EB0A1E] bg-red-50 border border-red-100 px-3 py-1 rounded">
            Knowledge Base
          </span>
          <h1 className="text-4xl font-black text-slate-900 tracking-tight pt-2">Frequently Asked Questions</h1>
          <p className="text-slate-500 text-sm max-w-lg mx-auto leading-relaxed">
            Quick help. Learn about our direct booking discounts, refund policies, registration timelines, and exchange bonuses.
          </p>
        </div>

        {/* FAQs list */}
        <div className="space-y-4">
          {FAQS_LIST.map((faq, i) => (
            <div key={i} className="bg-white border border-slate-200/80 rounded-2xl overflow-hidden shadow-sm">
              <button
                onClick={() => setOpenIndex(openIndex === i ? null : i)}
                className="w-full text-left px-6 py-5 font-extrabold text-sm text-slate-900 flex justify-between items-center focus:outline-none"
              >
                {faq.q}
                <ChevronDown className={`w-4 h-4 text-slate-400 transition-transform ${openIndex === i ? 'rotate-180 text-[#EB0A1E]' : ''}`} />
              </button>
              {openIndex === i && (
                <div className="px-6 pb-5 text-xs text-slate-600 leading-relaxed border-t border-slate-50 pt-4">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Still have questions? */}
        <div className="bg-slate-950 text-white p-6 rounded-2xl text-center space-y-3 shadow-md flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <AlertCircle className="w-8 h-8 text-[#EB0A1E] shrink-0" />
            <div className="text-left">
              <h4 className="text-sm font-extrabold">Still have questions?</h4>
              <p className="text-xs text-slate-400">Get in touch with our relations desk for fast assistance.</p>
            </div>
          </div>
          <Link href="/contact" className="bg-[#EB0A1E] hover:bg-red-750 text-white px-6 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wider transition-colors shrink-0">
            Submit inquiry
          </Link>
        </div>

      </div>
    </div>
  );
}
